### PR TITLE
Hopefully this adds the information you needed

### PR DESCRIPTION
**Pull request by spaceFountain**
I ended up probably adding more information than you really need an in a bit of a strange way. HolderVerReason can probably be removed, but I figured it didn't do any harm and might help at some point.

Basically this does two things.

1. Adds logging to verifyHolder in the case of success
1. Has verifyLocation record the log even in the case of success.

In the course of misunderstanding what the issue was I also had verifyHolder return a enum describing the reason for verification or failure which is added to the log messages.

This has not been tested beyond compiling as I don't have multiple people to test with. It should work properly, but I can't be sure.

### CODE REVIEW

**Comment by rourke750** [comment]
Look's awesome thx a lot for this

**Comment by ttk2** [comment]
should I put the pp version on Civtest on Civcraft?

**Comment by rourke750** [comment]
Put it on the citadel one.

**Comment by ttk2** [comment]
the jar on Civtest is specifically labeled for citadel 2.0 should I just
pull off of Jenkins instead?

**Comment by rourke750** [comment]
The civtest one can go on Civcraft if you are not updating to citadel 3.0
tomorrow. This one is being built on jenkins should go on the citadel 3.0
test server

**Comment by ttk2** [comment]
updated PP on the 3.0 testing server, staged new pp on Civcraft

**Comment by spaceFountain** [comment]
Just make sure someone gets on the test server to do at least some basic testing before this goes live. There's no reason it shouldn't work, but if I got something wrong there's the potential for it to lead to pearls getting freed. I'll be busy with school stuff till probably after dinner, but I can hop on then if anyone's will to pearl me. When does verifyLocation() get called? Just on restart or anytime someone checks where their pearl is being held?

**Comment by ttk2** [comment]
I think both, let me test it

**Comment by ttk2** [comment]
tested, worked just fine, pearled, summoned, returned, restarted, fed

**Pull request merged**
