### PR TITLE
Upgrade build to 1.7

### PR DESCRIPTION
**Pull request by ProgrammerDan**
java 1.7 as minimum target.

@rourke750 if you're cool with it, take lead on merge as this upgrade is your rodeo :)

### CODE REVIEW

**Comment by rourke750** [comment]
Also just so you https://github.com/Civcraft/PrisonPearl/blob/java-1.7/pom.xml#L28 thats the line you should add to poms that dont have it.

**Comment by ProgrammerDan** [comment]
Right on. I'll look for it.

**Comment by WildWeazel** [comment]
I want Java 6 gone as much as the next guy but when I made these poms @erocs suggested we use 6 for the publicly listed plugins (PP, Citadel, JukeAlert) because supposedly that's what most MC servers run.

**Comment by ProgrammerDan** [comment]
I find it hard to believe that is still the case.

**Comment by erocs** [comment]
I believe with 1.8 they moved up to jre1.7, which of course is now EOL.
Definitely move up to at least jre1.7 now. We should check if they moved up
to jre1.8 yet.

**Comment by ttk2** [comment]
We are running Java 8 on the server with absolutely no problem, go as far ahead as you need to.

**Comment by erocs** [comment]
We aren't the only ones to use the plugins.

**Comment by ProgrammerDan** [comment]
1.7 is probably a safe choice until the end of the year, by 2016 we should be 1.8 across the board.

That said, this group is sourcing the plugins, if upgrading negatively impacts other groups they can fork and downgrade.

**Comment by erocs** [comment]
The skill level of most MC server admins is rather low.

**Comment by rourke750** [comment]
That's insulting.

**Comment by ProgrammerDan** [comment]
@erocs Time for them to up their game :P 

2016 as a target for 1.8 is based on Oracle's likely path, though; eventually we need to move on, too. Java is a bad ship to sail with on outdated versions.

**Comment by erocs** [comment]
All I advocate is to preserve parity with the MC server itself. If Spigot
has moved to jdk1.8, then go for it. If we have an easy and documented way
via the dev VM to recompile the JARs for different jdk versions, then go
for it.

> That's insulting.

Welcome to the real world Rourke. Not everyone has the same levels of skill
with computers.

> Time for them to up their game :P

That's insulting and short sighted with regards to the potential user-base.
 :P

**Comment by rourke750** [comment]
> Welcome to the real world Rourke. Not everyone has the same levels of skill
with computers.

I'm just messing around.

**Comment by ProgrammerDan** [comment]
> All I advocate is to preserve parity with the MC server itself.

Reasonable. I think it's at 1.7, unless I'm mistaken.

**Comment by erocs** [comment]
I guess we don't maintain our dev.bukkit pages anymore. If those aren't
maintained our only users should be people who can compile so go with 1.8
if you want.

**Comment by rourke750** [comment]
Do we really need to really update.  As far as I know we dont user anything specific to .6, .7, .8 anyways.

**Comment by ProgrammerDan** [comment]
We might, and should. Keeping the compilation target up to date helps encourage use of new language features where appropriate.

**Comment by rourke750** [comment]
http://mcstats.org/global/

We really don't need to worry about Java 1.6 as it isnt even 1 percent.  But as you can see there are still a lot using java 7 so lets stick to that for now.

**Comment by ttk2** [comment]
how much work will it be to get everything to 1.7?

**Comment by ProgrammerDan** [comment]
very little. Only reason I don't have all those pulls pending was I didn't want to trample on Rourke's feet as he's updating for MC 1.8.7.

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
ok to test

**Pull request merged**
