### PR TITLE
Changing combat tag check to support CombatTagPlus

### PR DESCRIPTION
**Pull request by Maxopoly**
Fixing https://github.com/Civcraft/PrisonPearl/issues/65

@rourke750 That's how you wanted it, right?

### CODE REVIEW

**Comment by Maxopoly** [comment]
ok to test

**Comment by rourke750** [comment]
uh sort of, I want it to support both.

**Comment by Maxopoly** [comment]
Okay, changed it to work with both.

**Comment by rourke750** [comment]
perfect

**Pull request merged**
