### PR TITLE
removed durability as unique identifier

### PR DESCRIPTION
**Pull request by rourke750**
also fixed some issues with mercury

### CODE REVIEW

**Comment by rourke750** [comment]
@ttk2 Civtest pls, preferably just load an old map and drop this in it.

**Comment by rourke750** [comment]
ok to test

**Comment by ttk2** [comment]
up on civtest, should I make a testing thread? what sort of instructions should that have?

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
@ttk2 When would be a good day for you for this to go live?

**Comment by ttk2** [comment]
do we have a conversion script?

**Comment by ttk2** [comment]
or do I still need to write it? If its the later spec out exactly the
format we need in the DB

**Pull request merged**
