### PR TITLE
Add information to pearls and fix stuff on the way

### PR DESCRIPTION
**Pull request by Maxopoly**
Rework flatfile saving to use yml, add killer and death time to pearls and storage, improve usage of interfaces to no longer duplicate code

Untested so far, but will test before merging

### CODE REVIEW

**Comment by Maxopoly** [comment]
No comment means I can merge and do whatever I want?

**Comment by ProgrammerDan** [comment]
Probably :P

@rourke750 Anything?

@Maxopoly How'd testing go?

**Comment by Maxopoly** [comment]
Ok, this is completly tested and both flatfile and sql are working with all of this. While I was on it I also fixed a ton of issues with flatfile storage, it was barely functional.


Unless there are any objections, I'd say we merge this.

**Comment by ProgrammerDan** [comment]
If you've tested it I see no issues here, code looks clean, good refactors.

**Pull request merged**
